[package]
name = "rs-vulkan"
version = "0.1.0"
authors = ["Sergii Maksymov <sergii.maksymov@hs-anhalt.de>"]

[dependencies]
vulkano = "0.9"
vulkano-win = "0.9"
vulkano-shader-derive = "0.9.0"
winit = "0.11.0"

log = "0.4.1"
env_logger = "0.5.9"
